Add a fixer for bitsandbytes
nix-community/poetry2nix pull request #1128
Opened 2023-04-23 05:50 UTC by Atry

2023-05-01 11:55 UTC, cpcloud requested changes

2023-05-01 11:55 UTC, cpcloud commented on overrides/default.nix
> +          propagatedBuildInputs = (old.propagatedBuildInputs or [ ]) ++ [ self.setuptools ];
Can you move all of these `setuptools` additions to `build-systems.json`?

2023-05-01 11:55 UTC, cpcloud commented on overrides/default.nix
> +        propagatedBuildInputs = (old.propagatedBuildInputs or [ ]) ++ [ self.versioneer ];
This should also go in `build-systems.json`

2023-05-01 11:55 UTC, cpcloud commented on overrides/default.nix
> +            self.scikit-build
Any Python library that's needed to build or install the library, but not to run it, should go in `build-systems.json`.

2023-05-01 11:55 UTC, cpcloud commented on overrides/default.nix
> +      # );
Remove this if it isn't being used.

2023-05-01 11:55 UTC, cpcloud commented on overrides/default.nix
> +          propagatedBuildInputs = (old.propagatedBuildInputs or [ ]) ++ [ self.setuptools ];
Needs to go in `build-systems.json`

2023-05-01 11:55 UTC, cpcloud commented on overrides/default.nix
> +                  _arrow-cpp
Are you sure this is necessary?

2023-05-03 04:50 UTC, Atry commented on overrides/default.nix
> +                  _arrow-cpp
Yes, at least on macOS

2023-05-03 04:52 UTC, Atry commented
Most of the fixes have been added by other people in other PRs, so I simply removed them.

2023-05-03 17:13 UTC, cpcloud approved these changes

2023-05-03 17:13 UTC, merged