Switch jsonref to pdm
nix-community/poetry2nix pull request #1153
Opened 2023-05-04 01:55 UTC by Goorzhel

https://github.com/gazpachoking/jsonref/commit/9faf61eb8

2023-05-09 01:04 UTC, adisbladis commented
Could you add a version range guard to the change so older builds still work?

2023-05-10 03:38 UTC, adisbladis requested changes

2023-05-10 03:38 UTC, adisbladis commented on overrides/build-systems.json
> +      "until": "v1.1.0"
These shouldn't be prefixed with `v`.

2023-05-10 03:45 UTC, Goorzhel commented on overrides/build-systems.json
> +      "until": "v1.1.0"
Whoops.

2023-05-10 04:04 UTC, merged