PySide6 Darwin Compatibility
nix-community/poetry2nix pull request #1494
Opened 2024-01-11 02:02 UTC by CyborgPotato

[Contribution](README.md#contributing) checklist (recommended but not always applicable/required):

- [ ] There's an _[automated test](tests/default.nix)_ for this change
- [X] Commit messages or code include _references to related issues or PRs_ (including third parties)
- [X] Commit messages are _[conventional](https://www.conventionalcommits.org/)_ - examples from [the log](https://github.com/nix-community/poetry2nix/commits/master) include "feat: add changelog files to fixup hook", "fix(contourpy): allow wheel usage", and "test: add sqlalchemy2 test"

These changes make the wheels used to create pyside6 through poetry2nix able to run, the current derivation fails because of Linux specific packages such as speechd, and autoPatchelfcommands. I've tested with the majority of widgets and they appear to work on my machine.

Another issue that was run into is that the wheels that are used by default (regardless of preferWheel) cause an ordering conflict in the PythonPath, hence why pyside6 is overridden with a combined symlink tree of all the conflicting packages so that they all reside with the same priority in the same site-packages directory

2024-01-11 11:13 UTC, cpcloud requested changes
Thanks for the PR!

If there aren't already tests for these can you add them?

2024-01-11 11:13 UTC, cpcloud commented on overrides/default.nix
> +      } else old);
```suggestion
      });
```

2024-01-11 11:13 UTC, cpcloud commented on overrides/default.nix
> +      pyside6-essentials = super.pyside6-essentials.overridePythonAttrs (old: if stdenv.isLinux then {
```suggestion
      pyside6-essentials = super.pyside6-essentials.overridePythonAttrs (old: lib.optionalAttrs stdenv.isLinux {
```

2024-01-11 11:13 UTC, cpcloud commented on overrides/default.nix
> +      pyside6-addons = super.pyside6-addons.overridePythonAttrs (old: if stdenv.isLinux then {
```suggestion
      pyside6-addons = super.pyside6-addons.overridePythonAttrs (old: lib.optionalAttrs stdenv.isLinux {
```

2024-01-11 11:13 UTC, cpcloud commented on overrides/default.nix
> +      } else old);
```suggestion
      });
```

2024-01-11 14:39 UTC, CyborgPotato reviewed
Thank you for looking it over! I've moved the pyside6 to out of the Darwin exclusive set, and applied your suggested changes

2024-01-12 11:58 UTC, cpcloud commented
@CyborgPotato It looks like the macos build is failing.

2024-01-12 22:36 UTC, CyborgPotato commented
The error from the failing [job](https://github.com/nix-community/poetry2nix/actions/runs/7490587868/job/20389949722?pr=1494) says:

> error: Missing suitable source/wheel file entry for pyside6

Which I am having difficulty reproducing on my machine (though I also don't have an x86_64 mac to test on). Any advice for this error?

2024-01-27 20:46 UTC, CyborgPotato commented
@cpcloud I have found why the macos build aggregate failed, the pyside6 pyproject file expected a version of pyside that requires macos >= 11, while nixpkgs defaults to 10.12, making it unable to fetch the appropriate wheel.

2024-05-01 13:24 UTC, cpcloud commented
Closing in favor of #1621.

2024-05-01 13:24 UTC, closed without merging