overrides: update build system for propcache
nix-community/poetry2nix pull request #1847
Opened 2024-10-14 01:00 UTC by davejames

python versions <= 3.11 require tomli at build
https://github.com/aio-libs/propcache/blob/f5ba26cc63f4069473cf322c1b1c1924dec941de/pyproject.toml#L8

[Contribution](README.md#contributing) checklist (recommended but not always applicable/required):

- [ ] There's an _[automated test](tests/default.nix)_ for this change
- [x] Commit messages or code include _references to related issues or PRs_ (including third parties)
- [x] Commit messages are _[conventional](https://www.conventionalcommits.org/)_ - examples from [the log](https://github.com/nix-community/poetry2nix/commits/master) include "feat: add changelog files to fixup hook", "fix(contourpy): allow wheel usage", and "test: add sqlalchemy2 test"

2024-10-16 10:14 UTC, cpcloud submitted a review, later dismissed

2024-10-16 10:15 UTC, cpcloud requested changes

2024-10-16 10:15 UTC, cpcloud commented on overrides/build-systems.json
> +    "tomli"
Since this is Python version specific it should go in `overrides/default.nix` and be selectively added to `nativeBuildInputs` using `lib.optionals`.

2024-10-17 10:16 UTC, cpcloud commented on overrides/build-systems.json
> +    "tomli"
Fixed

2024-10-17 10:16 UTC, cpcloud approved these changes

2024-10-25 11:43 UTC, davejames commented
@cpcloud rebased and resolved conflicts. the macos-13 test now passes too

2024-10-25 13:50 UTC, merged