Add support to the legacy Pypi API
nix-community/poetry2nix pull request #299
Opened 2021-05-10 18:46 UTC by nlewo

Some private repositories (such as Devpi) expose the legacy Pypi
API (https://warehouse.pypa.io/api-reference/legacy.html).

This commit adds a dedicated fetcher which basically queries this API
to get the URL pointing to the actual file.

Since Pypi still exposes this API, it has been possible to write a
test that uses this legacy API.

Fixes https://github.com/nix-community/poetry2nix/issues/277.

2021-05-10 22:19 UTC, adisbladis requested changes

2021-05-13 09:15 UTC, nlewo commented on lib.nix
> +        buildInputs = with pkgs; [ (python3.withPackages (p: [ p.requests ])) ];
@adisbladis I addressed all your comments.

2021-06-01 21:27 UTC, adisbladis commented
@nlewo As described in 106c4248ed5bb0e26d2a968e52f67d49a5dfb105 we have to ignore SSL certificate errors for backwards compatibility reasons (older pinned nixpkgs).

Otherwise things are looking good and I've rebased on latest master.

2021-06-01 21:32 UTC, merged

2021-06-02 06:20 UTC, nlewo commented
Oh ok, makes sense. Thank you.

2021-06-15 11:58 UTC, iwanb commented
> @nlewo As described in [106c424](https://github.com/nix-community/poetry2nix/commit/106c4248ed5bb0e26d2a968e52f67d49a5dfb105) we have to ignore SSL certificate errors for backwards compatibility reasons (older pinned nixpkgs).
> 
> Otherwise things are looking good and I've rebased on latest master.

I somehow still get a certificate error when trying this against a local mirror:
```
Reading index https://xxx/+simple/attrs
Traceback (most recent call last):
  File "/nix/store/0y8m1qlzga5f3jc9ya7zz5nivlbby11j-python3-3.9.4/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/nix/store/0y8m1qlzga5f3jc9ya7zz5nivlbby11j-python3-3.9.4/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/nix/store/0y8m1qlzga5f3jc9ya7zz5nivlbby11j-python3-3.9.4/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/nix/store/0y8m1qlzga5f3jc9ya7zz5nivlbby11j-python3-3.9.4/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/nix/store/0y8m1qlzga5f3jc9ya7zz5nivlbby11j-python3-3.9.4/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/nix/store/0y8m1qlzga5f3jc9ya7zz5nivlbby11j-python3-3.9.4/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/nix/store/0y8m1qlzga5f3jc9ya7zz5nivlbby11j-python3-3.9.4/lib/python3.9/http/client.py", line 1422, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/nix/store/0y8m1qlzga5f3jc9ya7zz5nivlbby11j-python3-3.9.4/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/nix/store/0y8m1qlzga5f3jc9ya7zz5nivlbby11j-python3-3.9.4/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/nix/store/0y8m1qlzga5f3jc9ya7zz5nivlbby11j-python3-3.9.4/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/iyjilck9c5i0pj219cjwyddsa6kff6dg-fetch_from_legacy.py", line 47, in <module>
    response = urllib.request.urlopen(
  File "/nix/store/0y8m1qlzga5f3jc9ya7zz5nivlbby11j-python3-3.9.4/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/nix/store/0y8m1qlzga5f3jc9ya7zz5nivlbby11j-python3-3.9.4/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/nix/store/0y8m1qlzga5f3jc9ya7zz5nivlbby11j-python3-3.9.4/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/nix/store/0y8m1qlzga5f3jc9ya7zz5nivlbby11j-python3-3.9.4/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/nix/store/0y8m1qlzga5f3jc9ya7zz5nivlbby11j-python3-3.9.4/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/nix/store/0y8m1qlzga5f3jc9ya7zz5nivlbby11j-python3-3.9.4/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>
```

Any idea how is that possible? I'm building with a flake. Trying it manually with the same Python works, but I do have the certificate installed at system level.

2021-06-30 19:29 UTC, nlewo commented
@iwanb hm, i don't understand how this could happen. Could you try to run the `legacy` test? From the poetry2nix, you would need to run 
```
nix-build tests/ -A legacy
```

Since it connects to pypi without any certificates, I'm wondering if it works for you.

2021-06-30 19:33 UTC, nlewo commented
Oh! I've actually been able to reproduce.

2021-06-30 19:44 UTC, nlewo commented
@iwanb it would be really nice if you could try with https://github.com/nix-community/poetry2nix/pull/329 :)