add override to fix collision with jupyter-core
nix-community/poetry2nix pull request #459
Opened 2021-12-09 14:41 UTC by vale981

2021-12-21 11:45 UTC, cpcloud requested changes

2021-12-21 11:45 UTC, cpcloud commented on overrides.nix
> +        rm -f $out/lib/python*/site-packages/__pycache__/jupyter.cpython-39.pyc
```suggestion
        rm -f $out/${super.sitePackages}/__pycache__/jupyter.cpython-*.pyc
```

2021-12-21 11:45 UTC, cpcloud commented on overrides.nix
> +        rm -f $out/lib/python*/site-packages/__pycache__/jupyter.cpython-39.pyc
```suggestion
        rm -f $out/${super.sitePackages}/__pycache__/jupyter.cpython-*.pyc
```

2021-12-21 11:45 UTC, cpcloud commented on overrides.nix
> +        rm -f $out/lib/python*/site-packages/jupyter.py
```suggestion
        rm -f $out/${super.sitePackages}/jupyter.py
```

2021-12-21 11:45 UTC, cpcloud commented on overrides.nix
> +        rm -f $out/lib/python*/site-packages/jupyter.py
```suggestion
        rm -f $out/${super.sitePackages}/jupyter.py
```

2021-12-24 20:30 UTC, adisbladis commented
I don't even see why this would be needed as we do set `meta.priority` in this case?

2021-12-28 04:22 UTC, adisbladis commented
Feel free to reopen once the problems have been fixed.

2021-12-28 04:22 UTC, closed without merging